export const SERVICE_INFORMATION_FIELDS = [
  { title: "Define This Service", key: "services" },
  { title: "Name Of The Service", key: "name" },
  { title: "Allocated Workspace", key: "workspace" },
  { title: "Contact Number", key: "number" },
  { title: "Service Type", key: "type" },
  { title: "Preferred Meeting Mode", key: "mode" },
  { title: "Reference Color", key: "color" },
  { title: "Duration", key: "duration" },
  { title: "Price", key: "price" },
  { title: "Pre-buffer", key: "pre-buffer" },
  { title: "Post-buffer", key: "post-buffer" },
  {
    title: "Include Buffer Time In Calendar Invite",
    key: "calendar",
  },
  { title: "Description", key: "description" },
  { title: "Visibility", key: "visibility" },
  { title: "Status", key: "status" },
];
